### ISSUE TITLE
Not expand that bottomsheet

### ISSUE THREAD

**Issue by isaacraja15** [pujiaxin33/JXBottomSheetTableView#1]
Hi, 
i try this code in our app but iphone 5 is working fine.
but iphone 6 not working who to fix 

![ezgif-2-ecee786ea2e1](https://user-images.githubusercontent.com/44321070/54904133-a1d38180-4f03-11e9-8351-b7deb6012c0b.gif)

**Comment by pujiaxin33** [comment]
Can you try this [https://github.com/pujiaxin33/JXBottomSheetView](https://github.com/pujiaxin33/JXBottomSheetView)
